/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

/**
 *
 * @author sakun
 */
public class Add extends javax.swing.JFrame {
       private Main mainForm;
    

    /**
     * Creates new form Add
     */
    public Add(Main mainForm) {
        this.mainForm = mainForm;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtfirstname = new app.bolivia.swing.JCTextField();
        txtlastname = new app.bolivia.swing.JCTextField();
        txtphoneno = new app.bolivia.swing.JCTextField();
        txtemail = new app.bolivia.swing.JCTextField();
        txtrelation = new app.bolivia.swing.JCTextField();
        btnsave = new rojerusan.RSMaterialButtonRectangle();
        btnback = new rojerusan.RSMaterialButtonRectangle();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtfirstname.setBackground(new java.awt.Color(239, 239, 239));
        txtfirstname.setBorder(null);
        getContentPane().add(txtfirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 83, 160, 20));

        txtlastname.setBackground(new java.awt.Color(239, 239, 239));
        txtlastname.setBorder(null);
        getContentPane().add(txtlastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 132, 160, 20));

        txtphoneno.setBackground(new java.awt.Color(239, 239, 239));
        txtphoneno.setBorder(null);
        getContentPane().add(txtphoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 179, 160, 20));

        txtemail.setBackground(new java.awt.Color(239, 239, 239));
        txtemail.setBorder(null);
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 226, 160, 20));

        txtrelation.setBackground(new java.awt.Color(239, 239, 239));
        txtrelation.setBorder(null);
        getContentPane().add(txtrelation, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 273, 160, 20));

        btnsave.setBackground(new java.awt.Color(137, 112, 197));
        btnsave.setBorder(null);
        btnsave.setText("ADD");
        btnsave.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 160, 40));

        btnback.setBackground(new java.awt.Color(0, 0, 0));
        btnback.setBorder(null);
        btnback.setText("back");
        btnback.setToolTipText("");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 379, 70, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add001.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        String firstName = txtfirstname.getText();
        String lastName = txtlastname.getText();
        String phoneNumber = txtphoneno.getText();
        String relation = txtrelation.getText();
        String email = txtemail.getText();

        Contact contact = new Contact(firstName, lastName, phoneNumber, relation, email, "");
        mainForm.addContact(contact);
  
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
            
            mainForm.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btnback;
    private rojerusan.RSMaterialButtonRectangle btnsave;
    private javax.swing.JLabel jLabel1;
    private app.bolivia.swing.JCTextField txtemail;
    private app.bolivia.swing.JCTextField txtfirstname;
    private app.bolivia.swing.JCTextField txtlastname;
    private app.bolivia.swing.JCTextField txtphoneno;
    private app.bolivia.swing.JCTextField txtrelation;
    // End of variables declaration//GEN-END:variables
}
