/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;
import javax.swing.ImageIcon;
import java.awt.Image;
/**
 *
 * @author sakun
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
//         addComponentListener(new java.awt.event.ComponentAdapter() {
//        @Override
//        public void componentShown(java.awt.event.ComponentEvent evt) {
//            // Load the original image
//            ImageIcon originalIcon = new ImageIcon("C:\\Users\\sakun\\OneDrive\\Documents\\NetBeansProjects\\phone2\\PhoneDirectoryApp002\\src\\main\\Resources\\images\\Frame 10.png");
//
//            // Scale the image with a smooth scaling algorithm
//            Image scaledImage = originalIcon.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
//
//            // Create a new ImageIcon with the scaled image
//            ImageIcon scaledIcon = new ImageIcon(scaledImage);
//
//            // Set the scaled image as the icon of the JLabel
//            jLabel1.setIcon(scaledIcon);
//        }
//    });
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtusername = new app.bolivia.swing.JCTextField();
        txtpassword = new javax.swing.JPasswordField();
        btnlogin = new rojerusan.RSMaterialButtonRectangle();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtusername.setBackground(new java.awt.Color(255, 253, 248));
        txtusername.setBorder(null);
        txtusername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 170, 20));

        txtpassword.setBackground(new java.awt.Color(255, 253, 248));
        txtpassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtpassword.setBorder(null);
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 246, 170, 20));

        btnlogin.setBackground(new java.awt.Color(194, 249, 99));
        btnlogin.setBorder(null);
        btnlogin.setForeground(new java.awt.Color(0, 0, 0));
        btnlogin.setText("Login");
        btnlogin.setFont(new java.awt.Font("Roboto Medium", 1, 20)); // NOI18N
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 190, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login01.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        String username = txtusername.getText();
        String password = new String(txtpassword.getPassword());

        // Check if the username is "abc" and the password is "123"
        if(username.equals("abc") && password.equals("123")) {
            // If the credentials are correct, open the Main form
            Main MainForm = new Main();
            MainForm.setVisible(true);
            // Close the Login form
            this.dispose();
        } else {
            // Display an error message if the credentials are incorrect
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid Username or Password");
        }
    }//GEN-LAST:event_btnloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btnlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField txtpassword;
    private app.bolivia.swing.JCTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
